language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.20"
  - "5.30"
  - "dev"
  - "blead"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'CREATE DATABASE test;' -U postgres
services:
  - mysql
  - postgresql
env:
  - MOGTEST_DBHOST=127.0.0.1 MOGTEST_DBUSER=root MOGTEST_DBPASS= MOGTEST_DBNAME=test
  - MOGTEST_DBTYPE=Postgres MOGTEST_DBHOST=127.0.0.1 MOGTEST_DBUSER=postgres MOGTEST_DBPASS= MOGTEST_DBNAME=test
  - MOGTEST_DBTYPE=SQLite MOGTEST_DBUSER= MOGTEST_DBNAME=/tmp/mogilefsdb
