language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.20"
  - "5.30"
  - "dev"
  - "blead"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - psql -c 'CREATE DATABASE test;' -U postgres
install:
  - cpan-install --deps       # installs prereqs, including recommends
before_script:
  - coverage-setup
script:
  - prove -v -l $(test-files)   # parallel testing
services:
  - mysql
  - postgresql
env:
  - MOGTEST_DBHOST=127.0.0.1 MOGTEST_DBUSER=root MOGTEST_DBPASS= MOGTEST_DBNAME=test
  - MOGTEST_DBTYPE=Postgres MOGTEST_DBHOST=127.0.0.1 MOGTEST_DBUSER=postgres MOGTEST_DBPASS= MOGTEST_DBNAME=test
  - MOGTEST_DBTYPE=SQLite MOGTEST_DBUSER= MOGTEST_DBNAME=/tmp/mogilefsdb
